config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'faq', to: 'pages#faq'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home

end

def about

end

def contact

end

def faq

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmegaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>

<html>

<head>

<title>Omega-App</title>

<!-- Normalize.css -->

<!-- <link rel="stylesheet" type=text/css href="preshy.css"> -->

<style>

Body {
    background: blue;
    text-align: center;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 12px;
    background-color: orange;
    text-color: white;

}

h1 {
    color: white;
    background-color: cornflowerblue;
}

p {
    color: pink;
    background-color: purple;
    margin: 80px;
    padding: 80px;
    border-style: Dashed;
    border-width: 3px;
    border-left-width: 10px;
    border-right-width: 10px;
    border-color: red;
}



</style>

</head>

<body>

<%= link_to 'Home', root_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Faq', faq_path %>

    <header id="bottom">
    <a href="#bottom">Down Below</a>
    </header>


<div id="top">

<h1>This is our About section</h1>

<p class="intro">Just Got Started</p>

<p class="intro">Again, life is good</p>

<p class="intro">Again, life is good</p>

<p>Databases are used to organize and capture large amounts of data, typically by inputting, storing, retrieving and managing the information. This course will focus on relational databases, which are widely used to store data and SQL, the language used to query the database.

</p>

</div>


<footer id="top">
<%= link_to 'Home', root_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Faq', faq_path %>

    <a href="#top">Take Me Up</a>

    copyright &copy 2020 Preshy Inc.

</footer>

</body>


</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>

<html>

<head>

<title>Omega-App</title>

<!-- Normalize.css -->

<!-- <link rel="stylesheet" type=text/css href="preshy.css"> -->

<style>

Body {
    background: blue;
    text-align: center;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 12px;
    background-color: orange;
    text-color: white;

}

h1 {
    color: white;
    background-color: cornflowerblue;
}

p {
    color: pink;
    background-color: purple;
    margin: 80px;
    padding: 80px;
    border-style: Dashed;
    border-width: 3px;
    border-left-width: 10px;
    border-right-width: 10px;
    border-color: red;
}



</style>

</head>

<body>

<%= link_to 'About', about_path %>
<%= link_to 'Home', root_path %>
<%= link_to 'Faq', faq_path %>

    <header id="bottom">
        <a href="#bottom">Down Below</a>
    </header>


<div id="top">

<h1>This is our Contact section</h1>

<p class="intro">Just Got Started</p>

<p class="intro">Again, life is good</p>

<p class="intro">Again, life is good</p>

<p>Databases are used to organize and capture large amounts of data, typically by inputting, storing, retrieving and managing the information. This course will focus on relational databases, which are widely used to store data and SQL, the language used to query the database.

</p>

</div>


<footer id="top">

<%= link_to 'About', about_path %>
<%= link_to 'Home', root_path %>
<%= link_to 'Faq', faq_path %>

    <a href="#top">Take Me Up</a>

    copyright &copy 2020 Preshy Inc.

</footer>

</body>


</html>

app/views/pages/faq.html.erb
<!DOCTYPE html>

<html>

<head>

<title>Omega-App</title>

<!-- Normalize.css -->

<!-- <link rel="stylesheet" type=text/css href="preshy.css"> -->

<style>

Body {
    background: blue;
    text-align: center;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 12px;
    background-color: orange;
    text-color: white;

}

h1 {
    color: white;
    background-color: cornflowerblue;
}

p {
    color: pink;
    background-color: purple;
    margin: 80px;
    padding: 80px;
    border-style: Dashed;
    border-width: 3px;
    border-left-width: 10px;
    border-right-width: 10px;
    border-color: red;
}



</style>

</head>

<body>

<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Home', root_path %>

    <header id="bottom">
        <a href="#bottom">Down Below</a>
    </header>


<div id="top">

<h1>This is our Faq section</h1>

<p class="intro">Just Got Started</p>

<p class="intro">Again, life is good</p>

<p class="intro">Again, life is good</p>

<p>Databases are used to organize and capture large amounts of data, typically by inputting, storing, retrieving and managing the information. This course will focus on relational databases, which are widely used to store data and SQL, the language used to query the database.

</p>

</div>


<footer id="top">

<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Home', root_path %>

    <a href="#top">Take Me Up</a>

    copyright &copy 2020 Preshy Inc.

</footer>

</body>


</html>

app/views/pages/home.html.erb
<!DOCTYPE html>

<html>

<head>

<title>Omega-App</title>

<!-- Normalize.css -->

<!-- <link rel="stylesheet" type=text/css href="preshy.css"> -->

<style>

Body {
    background: blue;
    text-align: center;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 12px;
    background-color: orange;
    text-color: white;

}

h1 {
    color: white;
    background-color: cornflowerblue;
}

p {
    color: pink;
    background-color: purple;
    margin: 80px;
    padding: 80px;
    border-style: Dashed;
    border-width: 3px;
    border-left-width: 10px;
    border-right-width: 10px;
    border-color: red;
}



</style>

</head>

<body>

<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Faq', faq_path %>

    <header id="bottom">
        <a href="#bottom">Down Below</a>
    </header>


<div id="top">

<h1>This is our Home Section</h1>

<p class="intro">Just Got Started</p>

<p class="intro">Again, life is good</p>

<p class="intro">Again, life is good</p>

<p>Databases are used to organize and capture large amounts of data, typically by inputting, storing, retrieving and managing the information. This course will focus on relational databases, which are widely used to store data and SQL, the language used to query the database.

</p>

</div>


<footer id="top">
<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Faq', faq_path %>

    <a href="#top">Take Me Up</a>

    copyright &copy 2020 Preshy Inc.

</footer>

</body>


</html>